const Images = {
    thunder: { uri: 'https://usagif.com/wp-content/uploads/rainy-22.gif' },
    cloudy: { uri: 'https://i.gifer.com/g1vA.gif' },
    rain: { uri: 'https://cdn.pixabay.com/animation/2023/06/25/21/55/21-55-38-961_512.gif' },
    clear_sky: { uri: 'https://phoneky.co.uk/thumbs/screensavers/down/places/lightatthe_8e1hv56b.gif' },
    snow: { uri: 'https://cdn.pixabay.com/animation/2023/03/01/02/30/02-30-02-751_512.gif' },
    cloud_gif: { uri: 'https://media4.giphy.com/media/zXRyo6HndNtbsJ0HyE/giphy.gifhttps://media2.giphy.com/media/Bw7ObNsGsO2Zh21esA/giphy.gif?cid=6c09b9527jp1t29o4pnhbuf5isyz7nhb3d8gptlznlwup1i5&ep=v1_stickers_related&rid=giphy.gif&ct=s' },
    clouds: require('../assets/Image/clouds.mp4'),
    thunder_Icon: require('../assets/Image/strom.gif'),
    drizzle_Icon: require('../assets/Image/rain.gif'),
    snow_Icon: require('../assets/Image/snow.gif'),
    rain_Icon: require('../assets/Image/rainfall.gif'),
    shower_Icon: require('../assets/Image/rainCloud.gif'),
    partial_cloud_Icon: require('../assets/Image/partialCloud.gif'),
    sleet_Icon: require('../assets/Image/sleet.gif'),
    clear_sky_Icon: require('../assets/Image/sun.gif'),
    clear_night_Icon: require('../assets/Image/moon.gif'),
    strom_rain_Icon: require('../assets/Image/stromRain.gif'),
    night_fog_Icon: require('../assets/Image/nightFog.gif'),
    day_fog_Icon: require('../assets/Image/dayFog.gif'),
    partial_night_Icon: require('../assets/Image/night.gif'),
    overcast_Icon: require('../assets/Image/cloudCloudy.gif'),
    heavy_rain__Icon: require('../assets/Image/heavyRain.gif'),
    light_rain_night_Icon: require('../assets/Image/lightRainNight.gif'),
    light_snow_Icon: require('../assets/Image/lightSnow.gif'),
    cloud_day_Icon: require('../assets/Image/cloudDay.gif'),
    cloud_night_Icon: require('../assets/Image/cloudNight.gif'),
    search_gif_Icon: require('../assets/Image/searchGif.gif'),
    fog: require('../assets/Image/fog.gif'),
}
export default Images;