const Images = {
    home_cook_logo: require('../assets/Images/homeCookLogo.png'),
    menu_bar: require('../assets/Images/menu.png'),
    bag_item: require('../assets/Images/bag1.png'),
    search: require('../assets/Images/search.png'),
    filter: require('../assets/Images/filter.png'),
    burger_main: require('../assets/Images/burgerMain.jpg'),
    chicken_krisper_burger: require('../assets/Images/chickenKrisperBurger.png'),
    veg_krisper_burger: require('../assets/Images/vegKrisperBurger.png'),
    tandoori_zinger_burger: require('../assets/Images/tandooriZingerBurger.png'),
    classic_zinger_burger: require('../assets/Images/classicZingerBurger.png'),
    chicken_whooper: require('../assets/Images/chickenWhooper.png'),
    veg_double_whooper: require('../assets/Images/vegDoubleWhooper.png'),
    veg: require('../assets/Images/veg.png'),
    non_veg: require('../assets/Images/nonVeg.png'),
    clock: require('../assets/Images/clock.png'),
    minus: require('../assets/Images/minus.png'),
    plus: require('../assets/Images/plus.png'),
    minus_mini: require('../assets/Images/minusMini.png'),
    plus_mini: require('../assets/Images/plusMini.png'),
    blur_minus_mini: require('../assets/Images/blurMinusMini.png'),
    blur_minus: require('../assets/Images/blurMinus.png'),
    bin: require('../assets/Images/bin.png'),
    empty_cart: require('../assets/Images/emptyCart.png'),
    add_item: require('../assets/Images/addItem.png'),
    five_star: require('../assets/Images/5star.png'),
    four_star: require('../assets/Images/4star.png'),
    three_star: require('../assets/Images/3star.png'),
    schezwan_margherita: require('../assets/Images/schezwanMargherita.png'),
    pizza_main: 'https://media.istockphoto.com/id/1349560847/photo/sausage-and-vegetable-pizza-on-dark-background.webp?b=1&s=170667a&w=0&k=20&c=3U-ZTi5CZPTu-CxDiWUlkkGxvK3L1dflPb4nyDVnkZM=',
    drinks_main: require('../assets/Images/drinksMain.png'),
    mazedar_makhni_Paneer: require('../assets/Images/mazedarMakhniPaneer.png'),
    sizzling_schezwan_chicken: require('../assets/Images/sizzlingSchezwanChicken.png'),
    mexican_fiesta: require('../assets/Images/mexicanFiesta.png'),
    nawabi_murg_makhni: require('../assets/Images/nawabiMurgMakhni.png'),
    margherita: require('../assets/Images/margherita.png'),
    dhabe_da_keema: require('../assets/Images/dhabeDaKeema.png'),
    triple_chicken_feast: require('../assets/Images/tripleChickenFeast.png'),
    mango_mojito: { uri: 'https://www.nutmegnanny.com/wp-content/uploads/2015/04/Mango-Mojito-picture.jpg.webp' },
    blue_mojito: { uri: 'https://i.pngimg.me/thumb/f/720/97479fafae744b2b9d71.jpg' },
    kaala_mojito: { uri: 'https://lh3.googleusercontent.com/BtAU0iryc74sYIf6PqP5WHByFSGlGj-xULmO7saUeFZESJiJI2jtT8YxZ0IjUqyKMwJjLUxGgiEmxWQd64mODGo4rj88istSB0xrN8Y=w512-rw' },
    virgin_mojito: { uri: 'https://english.cookknowledge.com/wp-content/uploads/2022/12/fresh-drink-with-green-lime_11zon.jpg' },
    watermelon_mojito: { uri: 'https://media.istockphoto.com/id/479079920/photo/watermelon-mojito.jpg?s=612x612&w=0&k=20&c=t4bKU9u87_0x3Rj7lGNGOTO4rET6BTHpQ2hFLkO95H8=' },
    nutella_shake: { uri: 'https://saltandbaker.com/wp-content/uploads/2022/05/Nutella-Milkshake-5.jpg' },
    toffee_smoothie: { uri: 'https://img.freepik.com/premium-photo/wooden-background-enhancing-aesthetic-appeal-indulgent-beverage-iced-chocolate-milk_908985-15288.jpg?size=626&ext=jpg&ga=GA1.1.941644514.1689225378&semt=ais' },
    cherry_vanilla_smoothie: { uri: 'https://weelicious.com/wp-content/uploads/2017/02/Cherry-Vanilla-Smoothie-1-2.jpg' },
    biryani_main: { uri: 'https://www.forbesindia.com/media/images/2021/Dec/img_175063_whyisbiryanigettingbrandedalloverthecountry.jpg' },
    spicy_chicken_dum_biryani: { uri: 'https://vismaifood.com/storage/app/uploads/public/e12/7b7/127/thumb__700_0_0_0_auto.jpg' },
    chicken_tikka_biryani: { uri: 'https://static.wixstatic.com/media/91e241_76e634b7ab52498e82533ba79b747b55~mv2.jpg/v1/fill/w_640,h_426,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/91e241_76e634b7ab52498e82533ba79b747b55~mv2.jpg' },
    egg_dum_biryani: { uri: 'https://i.pinimg.com/originals/8e/d2/7a/8ed27a73af483c00a4858a7ff2c3d4c7.jpg' },
    paneer_dum_biryani: { uri: 'https://i0.wp.com/blendofspicesbysara.com/wp-content/uploads/2020/05/00100lrPORTRAIT_00100_BURST20200513150846378_COVER-01.jpeg?resize=800%2C840&ssl=1' },
    veg_biryani: { uri: 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/veg-biryani-683x1024.jpg' },
    mushroom_biryani: { uri: 'https://production-media.gousto.co.uk/cms/mood-image/1485---10-Min-Mushroom-Biryani-With-Cucumber-Raita.jpg' },
    prawn_biryani: { uri: 'https://ashasme.com/wp-content/uploads/2021/05/PRAWN-BIRYANI-01.jpg' },
    fish_biryani: { uri: 'https://media.istockphoto.com/id/678126194/photo/fish-biryani-or-fish-rice-popular-indian-non-vegetarian-recipe-made-of-fish-marinated-with.jpg?s=612x612&w=0&k=20&c=8lQFmjyLm4TFJE_YiHiNuoSF_JiOPue8DraDq_dOFbA=' },
    dosa_main: { uri: 'https://media.istockphoto.com/id/1156896083/photo/cheese-masala-dosa-recipe-with-sambar-and-chutney-selective-focus.jpg?s=612x612&w=0&k=20&c=Wyy0uUGXfQn7JstC8w0DsxWJVGnqWUJUCG53a42UH9s=' },
    mysori_masala_dosa: { uri: 'https://i.pinimg.com/736x/2a/c1/51/2ac15169850a766390adcba3a6d28eef.jpg' },
    cheese_corn_dosa: { uri: 'https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/xnvswfdt/95f5006b-c005-4a2c-8b78-95109df06183.jpg' },
    chocolate_dosa: { uri: 'https://s3-ap-south-1.amazonaws.com/betterbutterbucket-silver/sonal-sardesai02018103111171133.jpeg' },
    chinese_chopsuey_dosa: { uri: 'https://jubileehills.udipisupahar.com/wp-content/uploads/2022/09/Spring_Dosa_636189550029592805.jpg' },
    mutton_kari_dosa: { uri: 'https://s3-ap-south-1.amazonaws.com/betterbutterbucket-silver/1440513880m3uTXrbXp7.jpeg' },
    chicken_kari_dosa: { uri: 'https://www.kannammacooks.com/wp-content/uploads/madurai-kari-dosai.jpg' },
    pav_bhaji_masala_dosa: { uri: 'https://i0.wp.com/cookingfromheart.com/wp-content/uploads/2016/09/Pav-Bhaji-Dosa-2.jpg?resize=720%2C543&ssl=1' },
    panner_masala_dosa: { uri: 'https://www.sanjanafeasts.co.uk/wp-content/uploads/2023/05/Paneer-Masala-Dosa-546x728.jpg' },
}
export default Images;